<a href="https://colab.research.google.com/github/canseel/gelecek-hayalim-wcode/blob/main/week4_2_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Gelecek Hayalim: W-Code 2.0 Veri Bilimi ve Yapay Zeka Atolyesi Homework Week 4-2**



Homework 1

Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype=int)


print("Array:", arr)
print("Boyut sayısı (ndim):", arr.ndim) #number of dimensions
print("Toplam eleman sayısı (size):", arr.size)


Array: [1 2 3 4 5]
Boyut sayısı (ndim): 1
Toplam eleman sayısı (size): 5


Homework 2

Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.


İki boyutlu array:

[[1,2,6,7],

[4,3,9,5]]




Üç boyutlu array:

[[[7,5,14],[21,8,11]],

[[8,6,20],[14,3,9]]]

In [5]:
import numpy as np

ikib = np.array([
    [1,2,6,7],[4,3,9,5]
    ])

print("Array:", ikib)
print("Boyut sayısı (ndim):", ikib.ndim)
print("Toplam eleman sayısı (size):", ikib.size)
print("Şekil (satır, sütun):", ikib.shape)


Array: [[1 2 6 7]
 [4 3 9 5]]
Boyut sayısı (ndim): 2
Toplam eleman sayısı (size): 8
Şekil (satır, sütun): (2, 4)


In [6]:
import numpy as np

ucb = np.array([[[7,5,14],[21,8,11]],
                   [[8,6,20],[14,3,9]]])

print("Array:", ucb)
print("Boyut sayısı (ndim):", ucb.ndim)
print("Toplam eleman sayısı (size):", ucb.size)
print("Şekil (satır, sütun):", ucb.shape)


Array: [[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut sayısı (ndim): 3
Toplam eleman sayısı (size): 12
Şekil (satır, sütun): (2, 2, 3)


Homework 3

İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.





İki boyutlu arraydaki 2 elemanına ulaşalım.

In [7]:
print(ikib[0, 1]) # 0. satır 1. sütun

2


İki boyutlu arraydaki 7 elemanına ulaşalım.

In [9]:
print(ikib[0, 3]) # 0. satır 3. sütun


7


Üç boyutlu arraydaki 9 elemanına ulaşalım.

In [11]:
print(ucb[1, 1, 2])

9




Üç boyutlu arraydaki 5 elemanına ulaşalım.

In [12]:
print(ucb[0, 0, 1])

5


Homework 4

Arrayler üzerinde slicing işlemi uygulayalım.

İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

In [13]:
print(ikib[0, 1:3])   #[0, 1:3] → 0. satır, 1. ve 2. sütunlar


[2 6]


İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

In [14]:
print(ikib[1, 1:4])   #[1, 1:4] → 1. satır, 1.den 4.ye kadar sütunlar


[3 9 5]


Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

In [15]:
print(ucb[0, 1, :]) #0. depth 1. satır tüm elemanlar


[21  8 11]


Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

In [16]:
print(ucb[1, 0, 1:3])  #1. depth 0. satır 1den 3e kadar sütunlar


[ 6 20]


Homework 5

5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [17]:
import numpy as np

# Rastgele 0 ve 1'lerden oluşan 5x3 arrayler
arr1 = np.random.randint(0, 2, (5, 3))
arr2 = np.random.randint(0, 2, (5, 3))

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)

#Satır bazında birleştirme
arr_vertical = np.vstack((arr1, arr2))
print("\nSatır bazında birleştirilmiş array (10x3):\n", arr_vertical)

#Sütun bazında birleştirme
arr_horizontal = np.hstack((arr1, arr2))
print("\nSütun bazında birleştirilmiş array (5x6):\n", arr_horizontal)


Array 1:
 [[0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 1]]

Array 2:
 [[0 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Satır bazında birleştirilmiş array (10x3):
 [[0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 1]
 [0 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sütun bazında birleştirilmiş array (5x6):
 [[0 0 1 0 1 1]
 [0 0 1 1 1 1]
 [0 1 0 1 1 1]
 [1 0 1 1 1 1]
 [0 1 1 1 1 1]]
